markdown: redcarpet
redcarpet:
  extensions: ["autolink", "tables", "strikethrough"]
permalink: /:year/:month/:day/:title 
title: King Jin
url: http://jinhe1314.github.io
githubEditBaseURL: https://github.com/pala/pala.github.com/edit/master/
subscribe: http://jinhe1314.github.io/atom.xml
exclude: [ README.md, newpost.rb ]
domain: jinhe1314.github.io
author: King Jin
email: gojinhe@gmail.com
twitterID: jinhe1314
googleAnalyticsID: UA-5531632-1
disqusShortname: jinhe1314
timezone: America/New_York
